import * as Core from './core.js';
import {ViolinSampler} from './sampler.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={source:null,raw:[],notes:[],title:'Violin arrangement',bpm:120,midi:null,originalBuffer:null,originalUrl:null,busy:false,cancel:false,undo:[],page:0,selected:-1,tab:'score',model:null,modelLib:null,score:null,scoreLib:null,scoreToken:0,job:0};
const sampler=new ViolinSampler();let toastTimer=0,renderTimer=0,rollBoxes=[];
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=t=>`${Math.floor(Math.max(0,t)/60)}:${String(Math.floor(Math.max(0,t)%60)).padStart(2,'0')}`;
const duration=()=>state.notes.length?Math.max(...state.notes.map(n=>n.start+n.duration)):0;
const name=()=>Core.safeName(state.title||'violin');
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3500)}
function status(s,type=''){const e=$('#status-box');e.textContent=s;e.className='status-box'+(type?' '+type:'')}
function progress(stage,pct,detail=''){const box=$('#progress-box');box.hidden=false;$('#progress-stage').textContent=stage;$('#progress-percent').textContent=Math.round(pct)+'%';$('#progress-fill').style.width=Core.clamp(pct,0,100)+'%';$('#progress-detail').textContent=detail}
function busy(value){state.busy=value;$('#convert-btn').disabled=value||!state.source;$('#file-input').disabled=value;$('#demo-btn').disabled=value;$('#export-audio').disabled=value||!state.notes.length;$('#cancel-btn').hidden=!value;$('#clear-btn').disabled=value}
function available(){const yes=state.notes.length>0;for(const id of ['play-btn','stop-btn','seek','export-audio','export-midi','export-xml','export-pdf','add-note'])$('#'+id).disabled=!yes;$('#ready-pill').textContent=yes?'作品已生成':'尚無作品';$('#ready-pill').classList.toggle('ready',yes);$('#score-count').textContent=state.notes.length+' NOTES';$('#play-title').textContent=yes?state.title:'等待音樂';$('#art-title').textContent=yes?state.title:'YOUR NEXT MASTERPIECE';$('#sheet-title').textContent=state.title;$('#edit-count').textContent=state.notes.length+' 個音符';$('#add-note').disabled=!state.source||state.busy;sampler.duration=duration();$('#clock').textContent=fmt(sampler.offset)+' / '+fmt(duration())}
function saveBlob(data,filename,type){const blob=data instanceof Blob?data:new Blob([data],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function getSettings(){const [low,high]=$('#range').value.split(',').map(Number);const [beats,beatType]=$('#meter').value.split('/').map(Number);return {mode:$('#mode').value,low,high,octaves:$('#octaves').checked,transpose:Number($('#transpose').value),bpm:Core.clamp(Number($('#bpm').value)||120,20,300),key:$('#key').value,beats,beatType,grid:Number($('#quantize').value),strength:Number($('#strength').value)/100,maxVoices:2}}
function audioSettings(){return {instrument:$('#instrument').value,speed:Number($('#speed').value),vibrato:Number($('#vibrato').value),reverb:Number($('#reverb').value),onStatus:s=>$('#sample-state').textContent=s}}
function resetSource(){state.cancel=true;state.job++;state.scoreToken++;sampler.stop();if(state.originalUrl)URL.revokeObjectURL(state.originalUrl);state.originalUrl=null;state.source=null;state.raw=[];state.notes=[];state.midi=null;state.originalBuffer=null;state.title='Violin arrangement';state.undo=[];state.selected=-1;state.page=0;$('#file-input').value='';$('#source-info').hidden=true;$('#source-player').hidden=true;$('#track-picker').hidden=true;$('#original-audio').removeAttribute('src');$('#original-audio').load();$('#score-root').innerHTML='<div class="empty-score"><span>𝄞</span><p>轉換完成後，樂譜將顯示於此</p></div>';$('#note-table').innerHTML='<tr><td colspan="5" class="empty-row">尚無音符</td></tr>';$('#progress-box').hidden=true;available();status('請匯入音樂，或載入示範旋律')}
function setSourceInfo(file,kind,extra=''){state.title=file.name.replace(/\.[^.]+$/,'')||'Violin arrangement';$('#source-name').textContent=file.name;$('#source-meta').textContent=[kind,extra].filter(Boolean).join(' · ');$('#source-info').hidden=false;$('#convert-btn').disabled=false}
async function openFile(file){if(!file||state.busy)return;resetSource();const job=state.job;try{
 if(file.size>250*1024*1024)throw Error('檔案超過 250 MB，請先裁切或壓縮');const ext=(file.name.split('.').pop()||'').toLowerCase();const ab=await file.arrayBuffer();if(job!==state.job)return;
 if(['mid','midi'].includes(ext)){
  const midi=Core.decodeMidi(ab);state.midi=midi;state.source={kind:'midi',file};state.bpm=midi.bpm;$('#bpm').value=midi.bpm;state.raw=midi.notes;setSourceInfo(file,'MIDI',`${midi.notes.length} 個音符`);const tracks=midi.tracks.filter(t=>t.notes.length);if(tracks.length>1){$('#track-picker').hidden=false;$('#track-select').innerHTML='<option value="all">全部樂器軌道</option>'+midi.tracks.map((t,i)=>t.notes.length?`<option value="${i}">${escapeHtml(t.name)} · ${t.notes.length} notes</option>`:'').join('')}status('MIDI 已讀取。可選擇軌道，直接生成小提琴編曲','success');
 }else if(['xml','musicxml','mxl'].includes(ext)){
  let xml=new TextDecoder().decode(ab);if(ext==='mxl'){if(file.size>20*1024*1024)throw Error('壓縮樂譜上限為 20 MB');const zip=await import('https://cdn.jsdelivr.net/npm/fflate@0.8.2/+esm');const files=zip.unzipSync(new Uint8Array(ab),{filter:f=>f.originalSize<20*1024*1024});let path=Object.keys(files).find(k=>k.endsWith('.musicxml')||k.endsWith('.xml')&&!k.includes('META-INF'));if(files['META-INF/container.xml']){const c=new DOMParser().parseFromString(new TextDecoder().decode(files['META-INF/container.xml']),'application/xml');path=c.querySelector('rootfile')?.getAttribute('full-path')||path}if(!path||!files[path])throw Error('找不到壓縮樂譜中的 MusicXML');xml=new TextDecoder().decode(files[path])}
  const score=Core.decodeMusicXML(xml);state.source={kind:'xml',file};state.raw=score.notes;state.bpm=score.bpm;$('#bpm').value=score.bpm;setSourceInfo(file,'MusicXML',`${score.notes.length} 個音符`);state.title=score.title||state.title;status('樂譜已讀取。可重新編曲、修正與輸出','success');
 }else{
  const ctx=await sampler.context();let buffer;try{buffer=await ctx.decodeAudioData(ab.slice(0))}catch{throw Error('瀏覽器無法解碼此音訊格式，請轉成 WAV、MP3 或 M4A 後重試')}
  if(job!==state.job)return;state.originalBuffer=buffer;state.originalUrl=URL.createObjectURL(file);state.source={kind:'audio',file};setSourceInfo(file,'音訊',`${fmt(buffer.duration)} · ${buffer.sampleRate} Hz`);$('#original-audio').src=state.originalUrl;$('#source-player').hidden=false;drawWaveform(buffer);status('音訊已載入。按「開始轉換」啟動本機 AI 音高辨識','success');
 }available();
 }catch(e){resetSource();status(e.message||String(e),'error');toast(e.message||'讀取失敗')}}
function drawWaveform(buffer){const c=$('#waveform');if(!c)return;const rect=c.getBoundingClientRect(),w=Math.max(100,rect.width||300),h=74,dpr=Math.min(devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;const g=c.getContext('2d');g.scale(dpr,dpr);g.clearRect(0,0,w,h);g.fillStyle='#f7f8f7';g.fillRect(0,0,w,h);const data=buffer.getChannelData(0),stride=Math.max(1,Math.floor(data.length/w));g.strokeStyle='#b49a73';g.lineWidth=1;g.beginPath();for(let x=0;x<w;x++){let min=1,max=-1;for(let i=x*stride;i<Math.min(data.length,(x+1)*stride);i+=Math.max(1,Math.floor(stride/100))){min=Math.min(min,data[i]);max=Math.max(max,data[i])}g.moveTo(x,h/2+min*h*.42);g.lineTo(x,h/2+max*h*.42)}g.stroke();g.strokeStyle='#dce0de';g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke()}
async function loadModel(){if(state.model)return state.model;if(state.modelLib)return state.modelLib;state.modelLib=(async()=>{progress('載入 AI 模型',3,'首次使用需下載開源模型與運算函式庫');const bp=await import('https://cdn.jsdelivr.net/npm/@spotify/basic-pitch@1.0.1/+esm');const model=new bp.BasicPitch('https://cdn.jsdelivr.net/npm/@spotify/basic-pitch@1.0.1/model/model.json');await model.model;state.model={...bp,model};return state.model})();try{return await state.modelLib}catch(e){state.modelLib=null;throw Error('AI 模型載入失敗，請確認網路連線，或改用 MIDI 輸入。'+(e?.message||''))}}
async function resample(buffer,limit){const len=Math.ceil(Math.min(buffer.duration,limit)*22050);const ctx=new OfflineAudioContext(1,len,22050),src=ctx.createBufferSource();src.buffer=buffer;src.connect(ctx.destination);src.start(0);return await ctx.startRendering()}
async function transcribe(buffer,job){const bp=await loadModel(),limit=Number($('#analyze-limit').value),mono=await resample(buffer,limit);if(job!==state.job||state.cancel)throw Error('已停止分析');const total=mono.duration,windowSize=22,overlap=.6,step=windowSize-overlap,notes=[];const threshold=Number($('#threshold').value)/100,minLength=Math.max(1,Math.round(Number($('#min-note').value)*22050/256));
 for(let start=0;start<total;start+=step){if(state.cancel||job!==state.job)throw Error('已停止分析');const end=Math.min(total,start+windowSize),from=Math.round(start*22050),to=Math.min(mono.length,Math.round(end*22050));const chunk=new AudioBuffer({length:to-from,sampleRate:22050,numberOfChannels:1});chunk.copyToChannel(mono.getChannelData(0).subarray(from,to),0);let frames=[],onsets=[],contours=[];
  await bp.model.evaluateModel(chunk,(f,o,c)=>{frames.push(...f);onsets.push(...o);contours.push(...c)},p=>progress('AI 音高辨識',5+85*(start/total+(end-start)/total*p),`正在分析 ${fmt(start)} – ${fmt(end)} / ${fmt(total)}`));
  const result=bp.noteFramesToTime(bp.addPitchBendsToNoteEvents(contours,bp.outputToNotesPoly(frames,onsets,threshold,threshold,minLength)));
  for(const n of result){const s=start+n.startTimeSeconds,d=n.durationSeconds;if(d<=0||s>=total)continue;const center=s+d/2;if(start>0&&center<start+overlap/2)continue;notes.push({pitch:n.pitchMidi,start:Math.max(0,s),duration:Math.min(d,total-s),velocity:Core.clamp(n.amplitude||.8,.1,1),pitchBends:n.pitchBends})}
  frames=null;onsets=null;contours=null;progress('AI 音高辨識',5+85*end/total,`${notes.length} 個候選音符`);await new Promise(r=>setTimeout(r,0));if(end>=total)break;
 }
 if(!notes.length)throw Error('未辨識到有效音符。請嘗試清晰獨奏音軌、降低靈敏度或改用 MIDI');return mergeTranscription(Core.normalize(notes));
}
function mergeTranscription(input){const out=[];for(const n of input){const match=out.find(x=>x.pitch===n.pitch&&Math.min(x.start+x.duration,n.start+n.duration)-Math.max(x.start,n.start)>Math.min(x.duration,n.duration)*.6);if(match){const end=Math.max(match.start+match.duration,n.start+n.duration);match.start=Math.min(match.start,n.start);match.duration=end-match.start;match.velocity=Math.max(match.velocity,n.velocity)}else out.push({...n})}return Core.normalize(out)}
function applyArrangement(){const opts=getSettings();if(!state.raw.length)throw Error('沒有可編曲的音符');let notes=Core.arrange(state.raw,opts);if(opts.grid)notes=Core.quantize(notes,opts.bpm,opts.grid,opts.strength);if(['melody','bass'].includes(opts.mode))notes=Core.preventOverlap(notes);if(!notes.length)throw Error('選擇的音域沒有可用音符，請調整音域或移調');state.notes=Core.normalize(notes);state.bpm=opts.bpm;state.undo=[];state.page=0;state.selected=-1;sampler.stop();sampler.offset=0;renderEverything();status(`已生成 ${state.notes.length} 個音符 · ${fmt(duration())} · ${opts.bpm} BPM`,'success')}
async function convert(){if(state.busy||!state.source)return;const job=state.job;state.cancel=false;busy(true);progress('準備轉換',0);try{if(state.source.kind==='audio'){state.raw=await transcribe(state.originalBuffer,job)}else if(state.source.kind==='midi'){const v=$('#track-select').value;state.raw=v==='all'||!v?state.midi.notes:state.midi.tracks[Number(v)].notes}if(job!==state.job||state.cancel)throw Error('已停止分析');progress('編曲與記譜',94,'調整小提琴音域與節奏');applyArrangement();progress('完成',100,'');setTimeout(()=>{if(job===state.job)$('#progress-box').hidden=true},900);toast('小提琴編曲已完成')}catch(e){status(e.message||String(e),'error');toast(e.message||'轉換失敗')}finally{busy(false)}}
function loadDemo(){resetSource();state.source={kind:'demo',file:{name:'弦之境 · 示範旋律.mid'}};state.title='弦之境 · 示範旋律';state.raw=Core.demo();state.bpm=120;$('#bpm').value=120;setSourceInfo(state.source.file,'示範旋律','原創練習旋律');applyArrangement();toast('示範旋律已載入')}
function pushUndo(){state.undo.push(state.notes.map(n=>({...n})));if(state.undo.length>20)state.undo.shift();$('#undo-btn').disabled=false}
function updateNote(index,patch){if(!state.notes[index])return;pushUndo();const n={...state.notes[index],...patch};if(n.pitch<0||n.pitch>127||n.start<0||n.duration<=0){state.notes=state.undo.pop();toast('請輸入有效的音符、時間與長度');return}state.notes[index]=n;state.notes=Core.normalize(state.notes);scheduleRender()}
function parsePitch(value){const str=String(value).trim();if(/^\d+$/.test(str))return Number(str);const m=/^([A-Ga-g])([#b♯♭]?)(-?\d+)$/.exec(str);if(!m)return NaN;const p={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1].toUpperCase()];return (Number(m[3])+1)*12+p+(m[2]==='#'||m[2]==='♯'?1:m[2]==='b'||m[2]==='♭'?-1:0)}
function renderEverything(){available();renderTable();renderPiano();scheduleScore()}
function scheduleRender(){available();renderTable();renderPiano();scheduleScore()}
function scheduleScore(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>renderScore().catch(e=>fallbackScore(e.message)),150)}
async function getScoreLib(){if(window.opensheetmusicdisplay)return window.opensheetmusicdisplay;if(state.scoreLib)return state.scoreLib;state.scoreLib=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/opensheetmusicdisplay@1.9.9/build/opensheetmusicdisplay.min.js';script.onload=()=>window.opensheetmusicdisplay?resolve(window.opensheetmusicdisplay):reject(Error('樂譜函式庫載入失敗'));script.onerror=()=>reject(Error('無法載入樂譜函式庫，仍可下載 MusicXML'));document.head.append(script)});try{return await state.scoreLib}catch(e){state.scoreLib=null;throw e}}
function scoreXML(){const o=getSettings();return Core.encodeMusicXML(state.notes,{...o,bpm:state.bpm,title:state.title,composer:'',grid:o.grid||4})}
async function renderScore(){if(!state.notes.length)return;const job=state.job,token=++state.scoreToken,root=$('#score-root');root.innerHTML='<div class="empty-score"><span>𝄞</span><p>正在排版五線譜…</p></div>';const xml=scoreXML();try{const lib=await getScoreLib();if(job!==state.job||token!==state.scoreToken)return;root.replaceChildren();const osmd=new lib.OpenSheetMusicDisplay(root,{autoResize:true,backend:'svg',drawTitle:false,drawComposer:false,drawPartNames:false,drawingParameters:'default',pageFormat:'Endless'});state.score=osmd;await osmd.load(xml);if(job!==state.job||token!==state.scoreToken)return;osmd.render()}catch(e){if(token===state.scoreToken)fallbackScore(e.message)}}
function fallbackScore(reason){const root=$('#score-root');if(!state.notes.length)return;const notes=state.notes.slice(0,32),w=Math.max(360,notes.length*31+70),h=155;const y=p=>76-(p-64)*3.5;let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="簡易音高預覽">`;for(let i=0;i<5;i++)svg+=`<line x1="35" y1="${48+i*14}" x2="${w-12}" y2="${48+i*14}" stroke="#72797b" stroke-width=".7"/>`;svg+='<text x="7" y="109" font-size="65" font-family="serif" fill="#222">𝄞</text>';notes.forEach((n,i)=>{const x=55+i*31,py=Core.clamp(y(n.pitch),20,130);svg+=`<ellipse cx="${x}" cy="${py}" rx="5.5" ry="3.7" transform="rotate(-18 ${x} ${py})" fill="#202a31"/><line x1="${x+5}" y1="${py}" x2="${x+5}" y2="${py-29}" stroke="#202a31" stroke-width="1"/><text x="${x}" y="145" text-anchor="middle" font-size="7" fill="#7b858a">${Core.noteName(n.pitch)}</text>`;for(let ly=34;ly>=py;ly-=14)svg+=`<line x1="${x-9}" y1="${ly}" x2="${x+9}" y2="${ly}" stroke="#666" stroke-width=".7"/>`;for(let ly=118;ly<=py;ly+=14)svg+=`<line x1="${x-9}" y1="${ly}" x2="${x+9}" y2="${ly}" stroke="#666" stroke-width=".7"/>`});svg+='</svg>';root.innerHTML=`<div style="overflow:auto">${svg}</div><p style="font-size:10px;color:#8b969b">簡易音高預覽（非正式五線譜）。${escapeHtml(reason||'')} 可下載 MusicXML 至 MuseScore 排版。</p>`}
function renderTable(){const rows=state.notes,per=40,pages=Math.max(1,Math.ceil(rows.length/per));state.page=Core.clamp(state.page,0,pages-1);const start=state.page*per;$('#note-table').innerHTML=rows.length?rows.slice(start,start+per).map((n,j)=>{const i=start+j;return `<tr data-index="${i}"><td><input aria-label="音高" data-field="pitch" value="${Core.noteName(n.pitch)}"></td><td><input aria-label="開始時間" type="number" min="0" step=".01" data-field="start" value="${n.start.toFixed(3)}"></td><td><input aria-label="音符長度" type="number" min=".01" step=".01" data-field="duration" value="${n.duration.toFixed(3)}"></td><td><input aria-label="力度" type="number" min="1" max="127" data-field="velocity" value="${Math.round(n.velocity*127)}"></td><td><button class="delete-note" aria-label="刪除音符" data-delete="${i}">×</button></td></tr>`}).join(''):'<tr><td colspan="5" class="empty-row">尚無音符</td></tr>';$('#page-notes').textContent=rows.length?`${state.page+1} / ${pages}`:'—';$('#prev-notes').disabled=state.page===0;$('#next-notes').disabled=state.page>=pages-1;$('#undo-btn').disabled=!state.undo.length}
function renderPiano(){const canvas=$('#piano-roll');if(!canvas)return;const notes=state.notes,low=55,high=Math.max(88,Math.min(100,...notes.map(n=>n.pitch))),row=11,top=29,left=51,total=duration();const zoom=Number($('#piano-zoom').value),px=32*zoom,w=Math.max(380,Math.min(16000,left+Math.ceil(total*px)+30)),h=top+(high-low+1)*row+10,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const g=canvas.getContext('2d');g.scale(dpr,dpr);g.fillStyle='#fff';g.fillRect(0,0,w,h);rollBoxes=[];if(!notes.length)return;const pitchY=p=>top+(high-p)*row;
 for(let p=low;p<=high;p++){const y=pitchY(p);g.fillStyle=[1,3,6,8,10].includes(p%12)?'#f2f3f2':'#fff';g.fillRect(0,y,w,row);g.strokeStyle='#e6e9e7';g.lineWidth=.5;g.beginPath();g.moveTo(0,y+row);g.lineTo(w,y+row);g.stroke();if(p%12===0||p%12===7){g.fillStyle='#75838a';g.font='9px sans-serif';g.fillText(Core.noteName(p),5,y+8)}}
 for(let t=0;t<=total+1;t+=Math.max(1,Math.ceil(total/160))){const x=left+t*px;if(x>w)break;g.strokeStyle=t%4===0?'#d3d9d9':'#e9eceb';g.beginPath();g.moveTo(x,top);g.lineTo(x,h);g.stroke();g.fillStyle='#87949a';g.font='9px sans-serif';g.fillText(fmt(t),x+2,17)}g.fillStyle='#eef0ef';g.fillRect(0,0,left,h);g.fillStyle='#f8f9f7';g.fillRect(0,0,w,top);g.strokeStyle='#dce0de';g.strokeRect(.5,.5,w-1,h-1);notes.forEach((n,i)=>{if(n.pitch<low||n.pitch>high)return;const x=left+n.start*px,y=pitchY(n.pitch)+1,nw=Math.max(3,n.duration*px-1);g.fillStyle=i===state.selected?'#a27c45':'#58788b';g.fillRect(x,y,nw,row-2);if(nw>28){g.fillStyle='#fff';g.font='9px sans-serif';g.fillText(Core.noteName(n.pitch),x+4,y+8)}rollBoxes.push({x,y,w:nw,h:row-2,index:i})})}
function selectedNote(index){state.selected=index;renderPiano();const n=state.notes[index];if(!n)return;$('#selected-note').innerHTML=`<b>${Core.noteName(n.pitch)}</b> · ${n.start.toFixed(2)}s · ${n.duration.toFixed(2)}s <button class="text-button" id="edit-selected">編輯此音符 →</button>`;$('#edit-selected').onclick=()=>{state.page=Math.floor(index/40);selectTab('edit');renderTable();$('#note-table tr[data-index="'+index+'"] input')?.focus()}}
function selectTab(tab){state.tab=tab;$$('[data-tab]').forEach(b=>{const on=b.dataset.tab===tab;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});$$('.tab-panel').forEach(e=>e.hidden=e.id!==tab+'-view');if(tab==='piano')renderPiano();if(tab==='score'&&state.notes.length&&!$('#score-root svg'))scheduleScore()}
function setupEvents(){
 $('#file-input').addEventListener('change',e=>openFile(e.target.files[0]));$('#clear-btn').onclick=resetSource;$('#demo-btn').onclick=loadDemo;$('#convert-btn').onclick=convert;$('#cancel-btn').onclick=()=>{state.cancel=true;status('正在停止分析…')};
 const drop=$('#dropzone');for(const ev of ['dragenter','dragover'])drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragging')});for(const ev of ['dragleave','drop'])drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragging')});drop.addEventListener('drop',e=>openFile(e.dataTransfer.files[0]));
 $('#transpose').oninput=e=>$('#transpose-value').textContent=(Number(e.target.value)>0?'+':'')+e.target.value;$('#strength').oninput=e=>$('#strength-value').textContent=e.target.value+'%';$('#threshold').oninput=e=>$('#threshold-value').textContent=(e.target.value/100).toFixed(2);$('#vibrato').oninput=e=>$('#vibrato-value').textContent=e.target.value+' ¢';$('#reverb').oninput=e=>$('#reverb-value').textContent=e.target.value+'%';
 $('#play-btn').onclick=async()=>{try{if(sampler.playing){sampler.pause();return}$('#play-btn').disabled=true;$('#sample-state').textContent='準備小提琴採樣…';await sampler.play(state.notes,audioSettings());$('#play-btn').textContent='Ⅱ';$('#play-btn').setAttribute('aria-label','暫停')}catch(e){status(e.message||String(e),'error');toast(e.message||'播放失敗')}finally{$('#play-btn').disabled=false}};
 $('#stop-btn').onclick=()=>sampler.stop();sampler.onStop=()=>{$('#play-btn').textContent='▶';$('#play-btn').setAttribute('aria-label','播放')};sampler.onTime=(p,d)=>{$('#clock').textContent=fmt(p)+' / '+fmt(d);$('#seek').value=d?Math.round(p/d*1000):0};
 $('#seek').oninput=e=>{const was=sampler.seek(duration()*Number(e.target.value)/1000);if(was)sampler.play(state.notes,audioSettings()).then(()=>{$('#play-btn').textContent='Ⅱ'}).catch(e=>status(e.message,'error'))};
 $('#instrument').onchange=()=>{if(sampler.playing)sampler.pause();sampler.samples=null;$('#sample-state').textContent='音色已切換，播放時載入採樣'};
 $('#speed').onchange=()=>{if(sampler.playing){sampler.pause();sampler.play(state.notes,audioSettings()).catch(e=>status(e.message,'error'))}};
 $$('[data-tab]').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));$('#rerender-btn').onclick=()=>renderScore();$('#piano-zoom').oninput=renderPiano;
 $('#piano-roll').onclick=e=>{const c=e.currentTarget,rect=c.getBoundingClientRect(),x=(e.clientX-rect.left)*c.width/rect.width/(devicePixelRatio||1),y=(e.clientY-rect.top)*c.height/rect.height/(devicePixelRatio||1);const hit=rollBoxes.slice().reverse().find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(hit)selectedNote(hit.index)};
 $('#note-table').addEventListener('change',e=>{const field=e.target.dataset.field;if(!field)return;const index=Number(e.target.closest('tr').dataset.index),v=field==='pitch'?parsePitch(e.target.value):Number(e.target.value);if(!Number.isFinite(v)){toast('音高格式例如 G4、C#5 或 MIDI 69');renderTable();return}updateNote(index,{[field]:field==='velocity'?Core.clamp(v/127,.05,1):v})});
 $('#note-table').onclick=e=>{const b=e.target.closest('[data-delete]');if(!b)return;pushUndo();state.notes.splice(Number(b.dataset.delete),1);scheduleRender()};
 $('#add-note').onclick=()=>{pushUndo();const end=duration();state.notes.push({pitch:69,start:end,duration:.5,velocity:.8});state.notes=Core.normalize(state.notes);state.page=Math.floor((state.notes.length-1)/40);scheduleRender()};
 $('#undo-btn').onclick=()=>{if(!state.undo.length)return;state.notes=state.undo.pop();scheduleRender()};$('#prev-notes').onclick=()=>{state.page--;renderTable()};$('#next-notes').onclick=()=>{state.page++;renderTable()};
 $('#export-midi').onclick=()=>{try{saveBlob(Core.encodeMidi(state.notes,{bpm:state.bpm,title:state.title,program:40}),name()+'.mid','audio/midi');toast('MIDI 已輸出')}catch(e){toast(e.message)}};
 $('#export-xml').onclick=()=>{try{saveBlob(scoreXML(),name()+'.musicxml','application/vnd.recordare.musicxml+xml');toast('MusicXML 已輸出')}catch(e){toast(e.message)}};
 $('#export-pdf').onclick=async()=>{try{selectTab('score');await renderScore();window.print()}catch(e){toast(e.message)}};
 $('#export-audio').onclick=async()=>{if(state.busy)return;busy(true);progress('小提琴採樣合成',0,'準備離線音訊');try{const data=await sampler.render(state.notes,audioSettings(),s=>progress('小提琴採樣合成',60,s));progress('完成',100,'WAV 已準備');saveBlob(data,name()+' - Violin.wav','audio/wav');toast('小提琴 WAV 已輸出')}catch(e){status(e.message||String(e),'error');toast(e.message||'音檔輸出失敗')}finally{busy(false);setTimeout(()=>$('#progress-box').hidden=true,900)}};
 window.addEventListener('beforeunload',()=>{sampler.stop();if(state.originalUrl)URL.revokeObjectURL(state.originalUrl)});window.addEventListener('resize',()=>{if(state.originalBuffer)drawWaveform(state.originalBuffer);if(state.tab==='piano')renderPiano()});
}
setupEvents();available();