import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Window} from 'happy-dom';
import {setTimeout as nativeTimeout} from 'node:timers';
globalThis.setTimeout=(fn,delay,...args)=>{const t=nativeTimeout(fn,delay,...args);if(delay>=2000)t.unref();return t};
const win=new Window({url:'http://localhost:8173/converter.html',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:false}});
const drawn=[];
win.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:(_,k)=>k==='fillText'?(text)=>drawn.push(text):()=>{},set:()=>true});
const html=await readFile(new URL('./converter.html',import.meta.url),'utf8');win.document.write(html);
for(const key of ['window','document','localStorage','DOMParser'])globalThis[key]=key==='window'?win:win[key];
globalThis.devicePixelRatio=3;
globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};
win.opensheetmusicdisplay={OpenSheetMusicDisplay:class{constructor(root){this.root=root}async load(xml){this.xml=xml}render(){this.root.innerHTML='<svg aria-label="test score"></svg>'}}};
const downloads=[];
URL.createObjectURL=blob=>{downloads.push(blob);return 'blob:test'};
URL.revokeObjectURL=()=>{};
await import('./converter.js');
const $=s=>win.document.querySelector(s);
const click=async s=>{await $(s).onclick?.({target:$(s)})};
const change=(selector,value)=>{const e=$(selector);e.value=String(value);e.dispatchEvent(new win.Event('change',{bubbles:true}))};
const noteInput=(field)=>'#note-table tr input[data-field="'+field+'"]';
const settle=()=>new Promise(resolve=>setTimeout(resolve,450));
test('workspace lifecycle: demo, title, edits, undo/redo, empty state and draft',async()=>{
 assert.ok($('#play-btn').disabled);
 await click('#demo-btn');assert.ok(!$('#play-btn').disabled);const count=$('#note-table').children.length;assert.ok(count>=20);
 $('#title').value='我的練習';$('#title').dispatchEvent(new win.Event('input'));
 change(noteInput('pitch'),'G9');assert.equal($(noteInput('pitch')).value,'G9');
 await click('#undo-btn');assert.equal($(noteInput('pitch')).value,'A4');
 await click('#redo-btn');assert.equal($(noteInput('pitch')).value,'G9');
 await click('[data-tab="piano"]');assert.ok(drawn.includes('G9'));
 change(noteInput('pitch'),'C-1');assert.ok(drawn.includes('C-1'));
 change(noteInput('duration'),'-1');assert.ok(Number($(noteInput('duration')).value)>0);
 change('#transpose',12);await click('#arrange-btn');const arranged=$(noteInput('pitch')).value;
 await click('#undo-btn');assert.equal($(noteInput('pitch')).value,'C-1');
 await click('#redo-btn');assert.equal($(noteInput('pitch')).value,arranged);
 await click('#export-project');const saved=JSON.parse(await downloads.at(-1).text());
 assert.equal(saved.title,'我的練習');assert.equal(saved.raw[0].pitch,69);assert.notEqual(saved.notes[0].pitch,69);
 await settle();const draft=JSON.parse(localStorage.getItem('violin-atlas-converter-draft-v1'));
 assert.equal(draft.version,2);assert.equal(draft.notes.length,saved.notes.length);
 await click('#restore-draft');await click('#arrange-btn');assert.equal($(noteInput('pitch')).value,arranged);
 // A failed replacement leaves the visible edited work and the saved draft intact.
 const invalid=new win.File(['garbage'],'bad.mid',{type:'audio/midi'});
 $('#file-input').files=[invalid];$('#file-input').dispatchEvent(new win.Event('change'));await settle();
 assert.equal($('#play-title').textContent,'我的練習');assert.equal($('#note-table').children.length,saved.notes.length);
 assert.match($('#status-box').textContent,/現有作品已保留/);
 await click('#new-btn');assert.equal($('#play-btn').disabled,true);assert.equal($('#add-note').disabled,false);
 await click('#add-note');assert.equal($('#note-table').children.length,1);
 $('#note-table').onclick({target:$('#note-table [data-delete]')});await settle();
 assert.equal($('#play-btn').disabled,true);assert.match($('#score-root').textContent,/新增音符/);
 await click('#undo-btn');assert.equal($('#play-btn').disabled,false);
 await click('#clear-btn');assert.equal($('#convert-btn').disabled,true);assert.equal($('#undo-btn').disabled,true);
 assert.equal(localStorage.getItem('violin-atlas-converter-draft-v1'),null);
});
test('tabs use roving keyboard focus',()=>{
 const tabs=[...win.document.querySelectorAll('[data-tab]')];
 tabs[0].onkeydown({key:'ArrowRight',preventDefault(){}});
 assert.equal(tabs[1].getAttribute('aria-selected'),'true');assert.equal(tabs[1].tabIndex,0);assert.equal(tabs[0].tabIndex,-1);
 assert.ok($('#piano-view').hidden===false);
});
test.after(async()=>{await win.happyDOM.abort();win.close()});
