import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Window} from 'happy-dom';
import {setTimeout as nativeTimeout} from 'node:timers';
globalThis.setTimeout=(fn,delay,...args)=>{const t=nativeTimeout(fn,delay,...args);if(delay>=2000)t.unref();return t};
const win=new Window({url:'http://localhost:8173/converter.html',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,enableJavaScriptEvaluation:false}});
const drawn=[];
win.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:(_,k)=>k==='fillText'?(text)=>drawn.push(text):()=>{},set:()=>true});
const html=await readFile(new URL('./converter.html',import.meta.url),'utf8');win.document.write(html);
for(const key of ['window','document','localStorage','DOMParser'])globalThis[key]=key==='window'?win:win[key];
globalThis.devicePixelRatio=3;
globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};
win.opensheetmusicdisplay={OpenSheetMusicDisplay:class{constructor(root){this.root=root}async load(xml){this.xml=xml}render(){this.root.innerHTML='<svg aria-label="test score"></svg>'}}};
const downloads=[];
URL.createObjectURL=blob=>{downloads.push(blob);return 'blob:test'};
URL.revokeObjectURL=()=>{};
await import('./converter.js');
const $=s=>win.document.querySelector(s);
const click=async s=>{await $(s).onclick?.({target:$(s)})};
const change=(selector,value)=>{const e=$(selector);e.value=String(value);e.dispatchEvent(new win.Event('change',{bubbles:true}))};
const noteInput=(field)=>'#note-table tr input[data-field="'+field+'"]';
const settle=()=>new Promise(resolve=>setTimeout(resolve,450));
test('workspace lifecycle: demo, title, edits, undo/redo, empty state and draft',async()=>{
 assert.ok($('#play-btn').disabled);
 await click('#demo-btn');assert.ok(!$('#play-btn').disabled);const count=$('#note-table').children.length;assert.ok(count>=20);
 $('#title').value='我的練習';$('#title').dispatchEvent(new win.Event('input'));
 change(noteInput('pitch'),'G9');assert.equal($(noteInput('pitch')).value,'G9');
 await click('#undo-btn');assert.equal($(noteInput('pitch')).value,'A4');
 await click('#redo-btn');assert.equal($(noteInput('pitch')).value,'G9');
 await click('[data-tab="piano"]');assert.ok(drawn.includes('G9'));
 change(noteInput('pitch'),'C-1');assert.ok(drawn.includes('C-1'));
 change(noteInput('duration'),'-1');assert.ok(Number($(noteInput('duration')).value)>0);
 change('#transpose',12);await click('#arrange-btn');const arranged=$(noteInput('pitch')).value;
 await click('#undo-btn');assert.equal($(noteInput('pitch')).value,'C-1');
 await click('#redo-btn');assert.equal($(noteInput('pitch')).value,arranged);
 await click('#export-project');const saved=JSON.parse(await downloads.at(-1).text());
 assert.equal(saved.title,'我的練習');assert.equal(saved.raw[0].pitch,69);assert.notEqual(saved.notes[0].pitch,69);
 await settle();const draft=JSON.parse(localStorage.getItem('violin-atlas-converter-draft-v1'));
 assert.equal(draft.version,2);assert.equal(draft.notes.length,saved.notes.length);
 await click('#restore-draft');await click('#arrange-btn');assert.equal($(noteInput('pitch')).value,arranged);
 // A failed replacement leaves the visible edited work and the saved draft intact.
 const invalid=new win.File(['garbage'],'bad.mid',{type:'audio/midi'});
 $('#file-input').files=[invalid];$('#file-input').dispatchEvent(new win.Event('change'));await settle();
 assert.equal($('#play-title').textContent,'我的練習');assert.equal($('#note-table').children.length,saved.notes.length);
 assert.match($('#status-box').textContent,/現有作品已保留/);
 await click('#new-btn');assert.equal($('#play-btn').disabled,true);assert.equal($('#add-note').disabled,false);
 await click('#add-note');assert.equal($('#note-table').children.length,1);
 $('#note-table').onclick({target:$('#note-table [data-delete]')});await settle();
 assert.equal($('#play-btn').disabled,true);assert.match($('#score-root').textContent,/新增音符/);
 await click('#undo-btn');assert.equal($('#play-btn').disabled,false);
 await click('#clear-btn');assert.equal($('#convert-btn').disabled,true);assert.equal($('#undo-btn').disabled,true);
 assert.equal(localStorage.getItem('violin-atlas-converter-draft-v1'),null);
});
test('tabs use roving keyboard focus',()=>{
 const tabs=[...win.document.querySelectorAll('[data-tab]')];
 tabs[0].onkeydown({key:'ArrowRight',preventDefault(){}});
 assert.equal(tabs[1].getAttribute('aria-selected'),'true');assert.equal(tabs[1].tabIndex,0);assert.equal(tabs[0].tabIndex,-1);
 assert.ok($('#piano-view').hidden===false);
});
test('multi-selection, batch edits, pagination and undo work together',async()=>{
 change('#transpose',0);change('#mode','all');await click('#demo-btn');await click('[data-tab="edit"]');
 const pick=(index,checked=true)=>{const e=$('#note-table [data-select="'+index+'"]');e.checked=checked;e.dispatchEvent(new win.Event('change',{bubbles:true}))};
 pick(0);pick(1);assert.match($('#selection-count').textContent,/已選 2 /);assert.equal($('#select-all').indeterminate,true);
 change('#batch-transpose',12);await click('#apply-transpose');assert.equal($(noteInput('pitch')).value,'A5');
 assert.equal($('#note-table tr[data-index="2"] input[data-field="pitch"]').value,'C5');
 await click('#undo-btn');assert.equal($(noteInput('pitch')).value,'A4');assert.match($('#selection-count').textContent,/已選 0 /);
 $('#select-all').checked=true;$('#select-all').dispatchEvent(new win.Event('change'));
 await click('#duplicate-selection');assert.equal($('#edit-count').textContent,'48 個音符');assert.match($('#selection-count').textContent,/已選 24 /);
 await click('#next-notes');assert.equal($('#page-notes').textContent,'2 / 2');
 assert.equal(win.document.querySelectorAll('#note-table [data-select]:checked').length,8);
 $('#select-all').checked=true;$('#select-all').dispatchEvent(new win.Event('change'));await click('#delete-selection');
 assert.equal($('#edit-count').textContent,'0 個音符');assert.equal($('#play-btn').disabled,true);
 await click('#undo-btn');assert.equal($('#edit-count').textContent,'48 個音符');assert.equal($('#play-btn').disabled,false);
 await click('#clear-btn');
});
test('A–B export clips notes and project backup keeps the entire piece and practice setup',async()=>{
 change('#mode','all');await click('#demo-btn');change('#region-start',.1);change('#region-end',1);
 $('#region-enabled').checked=true;$('#region-enabled').dispatchEvent(new win.Event('change'));
 $('#loop').checked=true;$('#metronome').checked=true;change('#count-in',2);change('#click-volume',20);
 await click('#select-region');assert.match($('#selection-count').textContent,/已選 3 /);
 change('#export-scope','region');await click('#export-csv');
 const csv=await downloads.at(-1).text();assert.match(csv,/69,A4,0.000000,0.275000/); // Demo is quantized to sixteenths.
 assert.equal(csv.trim().split('\r\n').length,4);
 await click('#export-midi');const {decodeMidi}=await import('./core.js');const midi=decodeMidi(await downloads.at(-1).arrayBuffer());
 assert.equal(midi.notes.length,3);assert.equal(midi.notes[0].start,0);
 await click('#export-xml');assert.match(await downloads.at(-1).text(),/片段/);
 await click('#export-project');const project=JSON.parse(await downloads.at(-1).text());
 assert.equal(project.notes.length,24);assert.equal(project.practice.start,.1);assert.equal(project.practice.end,1);assert.equal(project.practice.countIn,2);assert.equal(project.practice.loop,true);
 await settle();await click('#restore-draft');assert.equal($('#region-enabled').checked,true);assert.equal($('#metronome').checked,true);assert.equal($('#region-start').value,'0.1');assert.equal($('#count-in').value,'2');
 // Bad range is rejected instead of silently exporting the full work.
 change('#region-end',.01);change('#export-scope','region');const count=downloads.length;await click('#export-csv');assert.equal(downloads.length,count);assert.match($('#toast').textContent,/有效 A–B/);
 await click('#region-reset');assert.equal($('#region-enabled').checked,false);
 await click('#clear-btn');
});
test('stale sample loading cannot unlock or restart a newer playback request',async()=>{
 const {ViolinSampler}=await import('./sampler.js'),proto=ViolinSampler.prototype;
 const oldLoad=proto.load,oldContext=proto.context,pending=[];
 const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){}});
 const node=()=>({gain:param(),frequency:param(),playbackRate:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),connect(){},disconnect(){},start(){},stop(){}});
 const ctx={currentTime:0,sampleRate:44100,destination:{},createGain:node,createDynamicsCompressor:node,createBufferSource:node,createOscillator:node,createConvolver:node,createBuffer:(_c,len)=>({getChannelData:()=>new Float32Array(len)})};
 proto.context=async function(){this.ctx=ctx;return ctx};proto.load=()=>new Promise(resolve=>pending.push(resolve));
 try{
  await click('#demo-btn');const first=click('#play-btn');assert.equal($('#play-btn').disabled,true);
  await click('#stop-btn');assert.equal($('#play-btn').disabled,false);
  const second=click('#play-btn');assert.equal($('#play-btn').disabled,true);
  pending[0]([{pitch:69,buffer:{duration:1}}]);await first;assert.equal($('#play-btn').disabled,true);
  pending[1]([{pitch:69,buffer:{duration:1}}]);await second;assert.equal($('#play-btn').disabled,false);assert.equal($('#play-btn').getAttribute('aria-label'),'暫停');
  await click('#stop-btn');assert.equal($('#play-btn').getAttribute('aria-label'),'播放');
 }finally{await click('#stop-btn');await click('#clear-btn');proto.load=oldLoad;proto.context=oldContext}
});
test.after(async()=>{await win.happyDOM.abort();win.close()});
